version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: KHL
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5433:5432"  # Измените это

  script:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/app/scripts
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Порт 5000 на хосте, 5000 в контейнере
    volumes:
      - .:/app  # Монтируем текущую директорию в /app
    environment:
      FLASK_ENV: development
    depends_on:
      - db

volumes:
  db_data:
